### ISSUE TITLE
Code Lab Feedback

### ISSUE THREAD

**Issue by KatieMFritz** [KatieMFritz/codelab-js-functions-strings-variables#1]
Hey @chrisvfritz, can you take a look at this? It's [hosted here](http://majestic-leather.surge.sh/).

This was easier than the first javascript lesson I did. Not sure if it's simply because I am getting used to looking at javascript, or if this is an easier problem to solve. 

A resource that helped me a lot was [https://www.daniweb.com/programming/web-development/threads/366368/javascript-noob-change-text-in-](https://www.daniweb.com/programming/web-development/threads/366368/javascript-noob-change-text-in-).

**Comment by chrisvfritz** [comment]
Thanks for sharing that resource! Is that something you think we should include somewhere in the lesson slides?

This project also looks good. It meets the criteria, but there are two tiny fixes I'd like you to make before I accept. Both your `index.html` and `scripts.js` file have a little bit of inconsistent indentation that I'd like you to fix. See if you can find it. If you're not seeing it, don't worry though - I'm happy to provide more direction!

**Comment by KatieMFritz** [comment]
Fixed. You could maybe include that link as a hint. Now that I'm looking at it again, though, I don't know if it's straightforward enough to use as instructions. I had to adapt it.

**Comment by chrisvfritz** [comment]
OK. I'll think about it or maybe find a similar resource - or maybe leave it as something folks can Google. :smiley: Looks great now! :shipit:
